export const ERROR_CODE = {
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  CREATE_ACCOUNT_ERROR: "CREATE_ACCOUNT_FAILED",
  INVALID_FORM_DATA: "INVALID_FORM_DATA",
  INVALID_USER: "INVALID_USER",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
} as const;
