export const ERROR_CODE = {
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  CHANGE_LOCALE_ERROR: "CHANGE_LOCALE_ERROR",
  CREATE_ACCOUNT_ERROR: "CREATE_ACCOUNT_FAILED",
  INVALID_FORM_DATA: "INVALID_FORM_DATA",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  INVALID_USER: "INVALID_USER",
  LOCALE_NOT_SUPPORTED: "LOCALE_NOT_SUPPORTED",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  SET_CART_ERROR: "SET_CART_ERROR",
} as const;
